---

- hosts: all
  sudo: yes
  roles:
    - gotofbi.vsftpd
  vars:
    vsftpd_service_enabled: yes
    vsftpd_service_state: started
    vsftpd_users:
       - username: ftpuser
         name: FTP User
         password: '$1$somesalt$jezmI5TSY7mVTzHLgsK5L.'